/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.restapi.apis

import com.gravatar.restapi.models.Avatar
import retrofit2.Response
import retrofit2.http.GET
import retrofit2.http.Header

internal interface AvatarsApi {
    /**
     * List avatars
     * Retrieves a list of available avatars for the authenticated user.
     * Responses:
     *  - 200: Successful retrieval of avatars
     *
     * @param authorization Bearer token (OAuth) to authenticate the request.
     * @return [kotlin.collections.List<Avatar>]
     */
    @GET("me/avatars")
    suspend fun getAvatars(
        @Header("Authorization") authorization: kotlin.String,
    ): Response<kotlin.collections.List<Avatar>>
}
