/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */
package com.gravatar.restapi.apis

import com.gravatar.restapi.models.Avatar
import com.gravatar.restapi.models.Identity
import com.gravatar.restapi.models.SelectAvatar
import retrofit2.Response
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.Header
import retrofit2.http.POST
import retrofit2.http.Path

internal interface IdentitiesApi {
    /**
     * # List avatars
     * curl -X GET --location "https://api.gravatar.com/v3/me/avatars" \
     * -H "Authorization: Bearer TOKEN"
     */
    @GET("me/avatars")
    suspend fun getAvatars(
        @Header("Authorization") authorization: kotlin.String,
    ): Response<List<Avatar>>

    /**
     * # Get details for your identity
     * # EMAIL_SHA256: should be your email's sha
     * curl -X GET --location "https://api.gravatar.com/v3/me/identities/EMAIL_SHA256" \
     * -H "Authorization: Bearer TOKEN"
     */
    @GET("me/identities/{emailHash}")
    suspend fun getIdentity(
        @Path("emailHash") emailHash: kotlin.String,
        @Header("Authorization") authorization: kotlin.String,
    ): Response<Identity>

    /**
     * # Set avatar for your identity
     * # EMAIL_SHA256: should be your email's sha
     * # IMAGE_ID comes from the List avatars endpoint
     * curl -X POST --location "https://api.gravatar.com/v3/me/identities/EMAIL_SHA256/avatar" \
     * -H "Authorization: Bearer TOKEN" \
     * -H "Content-Type: application/json" \
     * -d '{
     * "avatar_id": "IMAGE_ID"
     * }'
     */
    @POST("me/identities/{emailHash}/avatar")
    suspend fun setIdentityAvatar(
        @Path("emailHash") emailHash: kotlin.String,
        @Body avatarId: SelectAvatar,
        @Header("Authorization") authorization: kotlin.String,
    ): Response<Unit>
}
